[package]
name = "learning_wgpu"
version = "0.1.0"
edition = "2021"

[dependencies]
bytemuck = { version = "1.18.0", features = ["derive"] }
flume = "0.11.0"
smol = "2.0.2"
wgpu = { version = "22.1.0", features = ["vulkan-portability"] }
winit = "0.29.0"
